# Generated by Django 4.2.7 on 2023-11-20 16:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, verbose_name="наименование")),
                ("description", models.TextField(blank=True, max_length=512, verbose_name="описание")),
                ("image", models.ImageField(blank=True, null=True, upload_to=products.models.banner_directory_path)),
                ("archived", models.BooleanField(default=False, verbose_name="архивировано")),
            ],
            options={
                "verbose_name": "баннер",
                "verbose_name_plural": "баннеры",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="наименование")),
                ("slug", models.SlugField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                ("archived", models.BooleanField(default=False, verbose_name="архивировано")),
                ("is_active", models.BooleanField(default=True, verbose_name="активно")),
                ("foreground", models.BooleanField(default=False, verbose_name="приоритетный")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=products.models.category_icon_directory_path,
                        validators=[django.core.validators.FileExtensionValidator(["svg", "img", "png"])],
                        verbose_name="иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, verbose_name="наименование")),
            ],
            options={
                "verbose_name": "свойство продуктов",
                "verbose_name_plural": "свойства продуктов",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="производитель")),
                ("slug", models.SlugField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                ("archived", models.BooleanField(default=False, verbose_name="архивировано")),
            ],
            options={
                "verbose_name": "производитель",
                "verbose_name_plural": "производители",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, unique=True, verbose_name="наименование")),
                ("about", models.TextField(blank=True, max_length=512, verbose_name="краткое описание")),
                ("description", models.TextField(blank=True, max_length=1024, verbose_name="описание")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to=products.models.product_images_directory_path),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=128, verbose_name="значение")),
            ],
            options={
                "verbose_name": "значение свойства продуктов",
                "verbose_name_plural": "значения свойства продуктов",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to=products.models.product_images_directory_path),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="название тега")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("review_content", models.TextField(verbose_name="отзыв")),
                ("is_published", models.BooleanField(default=False, verbose_name="опубликовано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                ("archived", models.BooleanField(default=False, verbose_name="архивировано")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
    ]
