# Generated by Django 4.2.7 on 2023-12-11 18:01

from decimal import Decimal
import discount.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0003_alter_category_slug_category_unique_parent_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartPromo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="наименование скидки")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, verbose_name="подробное описание скидки"),
                ),
                (
                    "weight",
                    models.FloatField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="вес скидки",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=discount.models.promo_image_directory_path,
                        verbose_name="изображение",
                    ),
                ),
                ("active_from", models.DateField(verbose_name="действует от ")),
                ("active_to", models.DateField(verbose_name="действует до ")),
                ("is_active", models.BooleanField(default=False, verbose_name="скидка активна")),
                (
                    "items_from",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="кол-во товаров в корзине от"),
                ),
                (
                    "items_to",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="кол-во товаров в корзине до"),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="общая стоимость корзины от",
                    ),
                ),
                (
                    "price_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="общая стоимость корзины до",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="размер скидки в рублях",
                    ),
                ),
            ],
            options={
                "verbose_name": "скидка на корзину",
                "verbose_name_plural": "скидки на корзину",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCategorySet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="наименование набора")),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="products.category", verbose_name="набор категорий"),
                ),
                ("products", models.ManyToManyField(blank=True, to="products.product", verbose_name="набор товаров")),
            ],
            options={
                "verbose_name": "набор",
                "verbose_name_plural": "наборы",
            },
        ),
        migrations.CreateModel(
            name="SetPromo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="наименование скидки")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, verbose_name="подробное описание скидки"),
                ),
                (
                    "weight",
                    models.FloatField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="вес скидки",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=discount.models.promo_image_directory_path,
                        verbose_name="изображение",
                    ),
                ),
                ("active_from", models.DateField(verbose_name="действует от ")),
                ("active_to", models.DateField(verbose_name="действует до ")),
                ("is_active", models.BooleanField(default=False, verbose_name="скидка активна")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="размер скидки в рублях",
                    ),
                ),
                ("sets", models.ManyToManyField(blank=True, to="discount.productcategoryset", verbose_name="наборы")),
            ],
            options={
                "verbose_name": "скидка на наборы",
                "verbose_name_plural": "скидки на наборы",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductPromo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="наименование скидки")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, verbose_name="подробное описание скидки"),
                ),
                (
                    "weight",
                    models.FloatField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="вес скидки",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=discount.models.promo_image_directory_path,
                        verbose_name="изображение",
                    ),
                ),
                ("active_from", models.DateField(verbose_name="действует от ")),
                ("active_to", models.DateField(verbose_name="действует до ")),
                ("is_active", models.BooleanField(default=False, verbose_name="скидка активна")),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="размер скидки в процентах",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="categories_prodoctpromos",
                        to="products.category",
                        verbose_name="категории",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="products_prodoctpromos", to="products.product", verbose_name="товары"
                    ),
                ),
            ],
            options={
                "verbose_name": "скидка на продукт(ы) и/или категорию(ии)",
                "verbose_name_plural": "скидки на продукт(ы) и/или категорию(ии)",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="cartpromo",
            constraint=models.CheckConstraint(
                check=models.Q(("items_from__lte", models.F("items_to"))), name="items_from_lte_items_to"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartpromo",
            constraint=models.CheckConstraint(
                check=models.Q(("price_from__lte", models.F("price_to"))), name="price_from_lte_price_to"
            ),
        ),
        migrations.AddConstraint(
            model_name="setpromo",
            constraint=models.CheckConstraint(
                check=models.Q(("active_from__lt", models.F("active_to"))), name="setpromo_date_from_lt_date_to"
            ),
        ),
        migrations.AddConstraint(
            model_name="productpromo",
            constraint=models.CheckConstraint(
                check=models.Q(("active_from__lt", models.F("active_to"))), name="productpromo_date_from_lt_date_to"
            ),
        ),
    ]
