# Generated by Django 4.2.7 on 2023-11-20 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "default_price_from",
                    models.DecimalField(
                        decimal_places=2, default=10.0, max_digits=12, verbose_name="Дефолтная цена от"
                    ),
                ),
                (
                    "default_price_to",
                    models.DecimalField(
                        decimal_places=2, default=1000.0, max_digits=12, verbose_name="Дефолтная цена до"
                    ),
                ),
                ("default_sort", models.CharField(default="pk", verbose_name="Дефолтное поле для сортировки")),
                (
                    "default_sort_type",
                    models.CharField(
                        choices=[
                            ("famous", "По популярности"),
                            ("price", "По цене"),
                            ("review", "По отзывам"),
                            ("recency", "По новизне"),
                        ],
                        default="famous",
                        verbose_name="Дефолтный тип сортировки",
                    ),
                ),
                (
                    "default_sort_desc",
                    models.CharField(
                        choices=[("on", "Включена"), ("off", "Выключена")],
                        default="on",
                        verbose_name="Дефолтная сортировка по убыванию",
                    ),
                ),
                ("paginate_by", models.PositiveSmallIntegerField(default=8, verbose_name="Пагинация")),
                (
                    "pagination_on_each_side",
                    models.PositiveSmallIntegerField(default=2, verbose_name="Пагинация от центра"),
                ),
                ("pagination_on_ends", models.PositiveSmallIntegerField(default=1, verbose_name="Пагинация по краям")),
                (
                    "categories_list_cache_timeout",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="Время хранения кэша списка категорий, сек."
                    ),
                ),
                (
                    "banner_limit",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Максимальное количество баннеров",
                    ),
                ),
                (
                    "offer_limit",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[django.core.validators.MaxValueValidator(8)],
                        verbose_name="Максимальное количество предложений",
                    ),
                ),
                (
                    "foreground_category_limit",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MaxValueValidator(5)],
                        verbose_name="Максимальное количество избранных категорий",
                    ),
                ),
            ],
            options={
                "verbose_name": "settings",
                "verbose_name_plural": "settings",
            },
        ),
    ]
