# Generated by Django 4.2.7 on 2023-11-20 16:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shops.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="цена",
                    ),
                ),
                ("remains", models.PositiveIntegerField(verbose_name="остаток")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CARD", "Банковской картой"), ("CASH", "Наличными")],
                        default="CARD",
                        max_length=128,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("FREE", "Бесплатная доставка"),
                            ("REGULAR", "Обычная доставка"),
                            ("EXPRESS", "Экспресс доставка"),
                        ],
                        default="REGULAR",
                        max_length=128,
                        verbose_name="способ доставки",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "предложение магазина",
                "verbose_name_plural": "предложения магазина",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, verbose_name="название")),
                (
                    "about",
                    models.TextField(
                        default="Описание магазина",
                        help_text="Введите краткое описание магазина.",
                        verbose_name="Описание магазина",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="89001112233",
                        help_text="Контактный телефон магазина.",
                        max_length=11,
                        verbose_name="Телефон магазина",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Контактный емаил магазина.",
                        max_length=254,
                        null=True,
                        verbose_name="Емаил магазина",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(null=True, upload_to=shops.models.shop_avatar_path, verbose_name="Аватар"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="shops",
                        related_query_name="shop",
                        through="shops.Offer",
                        to="products.product",
                        verbose_name="товары в магазине",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shops", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "магазин",
                "verbose_name_plural": "магазины",
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="shop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shops.shop"),
        ),
    ]
