# Generated by Django 4.2.7 on 2023-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания заказа")),
                ("city", models.CharField(blank=True, max_length=50, verbose_name="Город доставки")),
                ("address", models.CharField(max_length=260, verbose_name="адрес доставки")),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("usually", "обычная доставка"), ("express", "экспресс-доставка")],
                        default=("usually", "обычная доставка"),
                        max_length=50,
                        verbose_name="метод доставки",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("card", "онлайн картой"), ("random", "Онлайн со случайного чужого счета")],
                        default=("card", "онлайн картой"),
                        max_length=50,
                        verbose_name="способ оплаты",
                    ),
                ),
                ("order_number", models.PositiveIntegerField(default=1, verbose_name="номер заказа")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "Success",
                                (
                                    ("создан", "создан"),
                                    ("выполнен", "выполнен"),
                                    ("доставляется", "доставляется"),
                                    ("оплачен", "оплачен"),
                                ),
                            ),
                            ("не оплачен", "не оплачен"),
                        ],
                        default="создан",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="общая стоимость")),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Количество товара")),
            ],
            options={
                "verbose_name": "заказ пользователя",
                "verbose_name_plural": "заказы пользователя",
            },
        ),
    ]
