# Generated by Django 4.2.7 on 2023-11-20 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="offer",
            field=models.ForeignKey(
                help_text="Выбрать желаемый товар по специальной цене от магазина",
                on_delete=django.db.models.deletion.CASCADE,
                to="shops.offer",
                verbose_name="Предложение",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="user_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="orders.order",
                verbose_name="Номер заказа пользователя",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
