# Generated by Django 4.2.7 on 2023-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Размер скидки"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Итоговая стоимость"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(check=models.Q(("total_price__gte", 1.0)), name="total_price_lte_1.00"),
        ),
    ]
