# Generated by Django 4.2.7 on 2023-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("usually", "обычная доставка"), ("express", "экспресс доставка")],
                default="usually",
                max_length=50,
                verbose_name="метод доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "онлайн картой"), ("random", "Онлайн со случайного чужого счета")],
                default="card",
                max_length=50,
                verbose_name="способ оплаты",
            ),
        ),
    ]
