# Generated by Django 4.2.7 on 2023-11-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer_from_api", models.JSONField(null=True, verbose_name="ответ сервиса оплаты")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата выполнения")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrecords",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "история оплаты заказа",
                "verbose_name_plural": "истории оплаты заказа",
                "ordering": ["-created_at"],
            },
        ),
    ]
